domain_path: C:\Users\nllil\Desktop\report4\platform\export\platform\sw\standalone_microblaze_I
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
